
server:
  port: 8081 # random port

spring:

  application:
    name: member-service
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 4d5deb7bab2f81566af27762cf47c6e8
            client-secret: UrdRXqMCQrmlWHC9fCcgoHMXD2HoFWtw
            #            redirect-uri: https://j7a603.p.ssafy.io/api/oauth2/callback/kakao
            redirect-uri: ${login-host}/oauth2/callback/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - account_email
              - profile_image
          naver:
            client-id: OQue5nz4eWJjpO9PSNY3
            client-secret: T98vh3ToEn
            redirect-uri: ${login-host}/oauth2/callback/naver
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile_image
          google:
            client-id: 867056260420-qm92mop4qnqtjl3dtt5bjfutpqbqoksa.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: ${login-host}/oauth2/callback/google
            scope:
              - profile
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

token:
  # 일단 하루
  expiration_time: 86400000
  secret: secretcode
  refresh-cookie-key: refresh

oauth2:
  # ????? ??
  #  authorizedRedirectUri: http://localhost:3000/oauth2/redirect
  authorizedRedirectUri: ${client-host}/oauth2/redirect

kafka-ip: 127.0.0.1:9092

login-host: http://localhost:8000/member-service

client-host: http://localhost:3000